"""add completed_steps to progress

Revision ID: b18a13aeaa01
Revises: 6d7d59403ef7
Create Date: 2025-07-25 14:46:08.219734

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b18a13aeaa01'
down_revision: Union[str, None] = '6d7d59403ef7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('progress', sa.Column('completed_steps', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('progress', 'completed_steps')
    # ### end Alembic commands ###
